# Generated by Django 5.2.7 on 2025-11-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_0', '0004_alter_dispositivo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
    ]
