# Generated by Django 5.2.7 on 2025-11-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_0', '0005_alter_dispositivo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='thingspeak_read_key',
            field=models.CharField(blank=True, help_text='Read API Key (privada, solo para actualización)', max_length=50, null=True),
        ),
    ]
