# Generated by Django 5.2.7 on 2025-11-09 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_0', '0006_dispositivo_thingspeak_read_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={},
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='thingspeak_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='thingspeak_read_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.FloatField(blank=True, null=True)),
                ('field2', models.FloatField(blank=True, null=True)),
                ('field3', models.FloatField(blank=True, null=True)),
                ('field4', models.FloatField(blank=True, null=True)),
                ('field5', models.FloatField(blank=True, null=True)),
                ('field6', models.FloatField(blank=True, null=True)),
                ('field7', models.FloatField(blank=True, null=True)),
                ('field8', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_lecturas', to='panel_0.dispositivo')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('dispositivo', 'creado_en')},
            },
        ),
    ]
