# Generated by Django 5.2.7 on 2025-11-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_0', '0007_alter_dispositivo_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lectura',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
