# Generated by Django 5.2.7 on 2025-11-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel_0', '0002_alter_dispositivo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=10)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='panel_0.dispositivo')),
            ],
            options={
                'indexes': [models.Index(fields=['dispositivo', 'campo'], name='analisis_le_disposi_323693_idx'), models.Index(fields=['timestamp'], name='analisis_le_timesta_81bb9a_idx')],
                'unique_together': {('dispositivo', 'campo', 'timestamp')},
            },
        ),
    ]
