# Generated by Django 5.2.8 on 2025-11-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lectura',
        ),
    ]
